// All translations for the entire website
const translations = {
    en: {
        // Nav & Hero
        home: "Home",
        myFarm: "My farm",
        toDoList: "To-Do List",
        localTrend: "Local Trend",
        feedback: "Feedback",
        search: "Search...",
        websiteLanguage: "Website Language:",
        heroTitle: "AgroKheti",
        heroSubtitle: "by PSA Content Desk",
        heroDate: "September 15, 2025",
        ctaButton: "Helping Farmers to build better",
        // Form
        formHeading: "Enter the Form Detail",
        voiceInputTitle: "Voice Input",
        voiceInputSubtitle: "Record your details in your local language.",
        formDetailsHeading: "Farm Details",
        submitBtn: "Submit",
        locationLabel: "Location",
        landSizeLabel: "Land Size",
        cropLabel: "Crop",
        soilTypeLabel: "Soil Type",
        soilCharacterLabel: "Soil Character",
        irrigationLabel: "Irrigation Source",
        sowingLabel: "Sowing Type",
        sowingDateLabel: "Sowing Date",
        cropStageLabel: "Crop Stage",
        problemLabel: "Current Problem",
        uploadImageLabel: "Upload Image",
        // Footer
        footerLogo: "AgroKheti",
        footerSchemes: "Schemes",
        footerMarketPrices: "Market Prices",
        footerContact: "Contact",
        // Dropdown Options
        locationOptions: ["Select Location", "Auto-detect GPS", "District A", "District B", "District C"],
        landSizeOptions: ["<1 acre", "1–5 acres", "5+ acres"],
        cropOptions: ["Wheat", "Rice", "Maize", "Soybean"],
        soilTypeOptions: ["Sandy", "Clay", "Loamy", "Black"],
        soilCharacterOptions: ["Select Soil Character", "Not Sure", "Black", "Red", "Yellow", "Brown", "High Fertility", "Low Fertility"],
        irrigationOptions: ["Canal", "Tube Well", "Rainfed", "Pond"],
        sowingOptions: ["Manual", "Machine"],
        cropStageOptions: ["Select Stage", "Seedling", "Vegetative", "Flowering", "Harvesting"],
        problemOptions: ["Select Problem", "Fertilizer Issue", "Irrigation Issue", "Disease", "Pest", "Other"]
    },
    hi: {
        // Nav & Hero
        home: "होम",
        myFarm: "मेरा खेत",
        toDoList: "कार्य सूची",
        localTrend: "स्थानीय रुझान",
        feedback: "फीडबैक",
        search: "खोजें...",
        websiteLanguage: "वेबसाइट भाषा:",
        heroTitle: "एग्रोखेती",
        heroSubtitle: "पी.एस.ए. कंटेंट डेस्क द्वारा",
        heroDate: "22 सितंबर, 2025",
        ctaButton: "किसानों को बेहतर बनाने में मदद",
        // Form
        formHeading: "फॉर्म विवरण दर्ज करें",
        voiceInputTitle: "ध्वनि इनपुट",
        voiceInputSubtitle: "अपनी जानकारी अपनी स्थानीय भाषा में रिकॉर्ड करें।",
        formDetailsHeading: "खेत का विवरण",
        submitBtn: "सबमिट करें",
        locationLabel: "स्थान",
        landSizeLabel: "भूमि का आकार",
        cropLabel: "फसल",
        soilTypeLabel: "मिट्टी का प्रकार",
        soilCharacterLabel: "मिट्टी का चरित्र",
        irrigationLabel: "सिंचाई स्रोत",
        sowingLabel: "बुवाई प्रकार",
        sowingDateLabel: "बुवाई की तिथि",
        cropStageLabel: "फसल का चरण",
        problemLabel: "वर्तमान समस्या",
        uploadImageLabel: "छवि अपलोड करें",
        // Footer
        footerLogo: "एग्रोखेती",
        footerSchemes: "योजनाएं",
        footerMarketPrices: "बाजार कीमतें",
        footerContact: "संपर्क",
        // Dropdown Options
        locationOptions: ["स्थान चुनें", "ऑटो-डिटेक्ट GPS", "जिला A", "जिला B", "जिला C"],
        landSizeOptions: ["<1 एकड़", "1–5 एकड़", "5+ एकड़"],
        cropOptions: ["गेहूं", "चावल", "मक्का", "सोयाबीन"],
        soilTypeOptions: ["रेतीली", "चिकनी", "दोमट", "काली"],
        soilCharacterOptions: ["मिट्टी का चरित्र चुनें", "सुनिश्चित नहीं", "काली", "लाल", "पीली", "भूरी", "उच्च उर्वरता", "कम उर्वरता"],
        irrigationOptions: ["नहर", "ट्यूबवेल", "वर्षा आधारित", "तालाब"],
        sowingOptions: ["हाथ से", "मशीन से"],
        cropStageOptions: ["चरण चुनें", "पौध", "वनस्पति", "फूल आना", "कटाई"],
        problemOptions: ["समस्या चुनें", "खाद की समस्या", "सिंचाई की समस्या", "रोग", "कीट", "अन्य"]
    },
    pa: {
        // Nav & Hero
        home: "ਮੁੱਖ ਪੰਨਾ",
        myFarm: "ਮੇਰਾ ਖੇਤ",
        toDoList: "ਕਰਨ ਵਾਲੀ ਸੂਚੀ",
        localTrend: "ਸਥਾਨਕ ਰੁਝਾਨ",
        feedback: "ਫੀਡਬੈਕ",
        search: "ਖੋਜ...",
        websiteLanguage: "ਵੈਬਸਾਈਟ ਭਾਸ਼ਾ:",
        heroTitle: "ਐਗਰੋਖੇਤੀ",
        heroSubtitle: "ਪੀਐਸਏ ਕੰਟੈਂਟ ਡੈਸਕ ਦੁਆਰਾ",
        heroDate: "22 ਸਤੰਬਰ, 2025",
        ctaButton: "ਕਿਸਾਨਾਂ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਵਿੱਚ ਮਦਦ",
        // Form
        formHeading: "ਫਾਰਮ ਵੇਰਵੇ ਦਰਜ ਕਰੋ",
        voiceInputTitle: "ਅਵਾਜ਼ ਇਨਪੁਟ",
        voiceInputSubtitle: "ਆਪਣੇ ਵੇਰਵੇ ਆਪਣੀ ਸਥਾਨਕ ਭਾਸ਼ਾ ਵਿੱਚ ਰਿਕਾਰਡ ਕਰੋ।",
        formDetailsHeading: "ਖੇਤ ਦੇ ਵੇਰਵੇ",
        submitBtn: "ਸਪੁਰਦ ਕਰੋ",
        locationLabel: "ਟਿਕਾਣਾ",
        landSizeLabel: "ਜ਼ਮੀਨ ਦਾ ਆਕਾਰ",
        cropLabel: "ਫ਼ਸਲ",
        soilTypeLabel: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
        soilCharacterLabel: "ਮਿੱਟੀ ਦਾ ਅੱਖਰ",
        irrigationLabel: "ਸਿੰਚਾਈ ਸਰੋਤ",
        sowingLabel: "ਬਿਜਾਈ ਕਿਸਮ",
        sowingDateLabel: "ਬਿਜਾਈ ਦੀ ਮਿਤੀ",
        cropStageLabel: "ਫ਼ਸਲ ਦਾ ਪੜਾਅ",
        problemLabel: "ਮੌਜੂਦਾ ਸਮੱਸਿਆ",
        uploadImageLabel: "ਚਿੱਤਰ ਅੱਪਲੋਡ ਕਰੋ",
        // Footer
        footerLogo: "ਐਗਰੋਖੇਤੀ",
        footerSchemes: "ਯੋਜਨਾਵਾਂ",
        footerMarketPrices: "ਬਜ਼ਾਰ ਕੀਮਤਾਂ",
        footerContact: "ਸੰਪਰਕ",
        // Dropdown Options
        locationOptions: ["ਟਿਕਾਣਾ ਚੁਣੋ", "ਆਟੋ-ਡਿਟੈਕਟ GPS", "ਜ਼ਿਲਾ A", "ਜ਼ਿਲਾ B", "ਜ਼ਿਲਾ C"],
        landSizeOptions: ["<1 ਏਕੜ", "1–5 ਏਕੜ", "5+ ਏਕੜ"],
        cropOptions: ["ਗੰਧੁਮ", "ਚੌਲ", "ਮੱਕੀ", "ਸੋਯਾਬੀਨ"],
        soilTypeOptions: ["ਰੇਤਲੀ", "ਚਿਕਣੀ", "ਦੋਮਟ", "ਕਾਲੀ"],
        soilCharacterOptions: ["ਮਿੱਟੀ ਦਾ ਅੱਖਰ ਚੁਣੋ", "ਯਕੀਨੀ ਨਹੀਂ", "ਕਾਲਾ", "ਲਾਲ", "ਪੀਲਾ", "ਭੂਰਾ", "ਉੱਚ ਉਪਜਾਊ ਸ਼ਕਤੀ", "ਘੱਟ ਉਪਜਾਊ ਸ਼ਕਤੀ"],
        irrigationOptions: ["ਨਹਿਰ", "ਟਿਊਬਵੈਲ", "ਵਰਖਾ ਆਧਾਰਿਤ", "ਪੋੰਡ"],
        sowingOptions: ["ਹੱਥ ਨਾਲ", "ਮਸ਼ੀਨ ਨਾਲ"],
        cropStageOptions: ["ਸਟੇਜ ਚੁਣੋ", "ਪੌਦਾ", "ਸਬਜ਼ੀ", "ਫੁੱਲ", "ਕਟਾਈ"],
        problemOptions: ["ਸਮੱਸਿਆ ਚੁਣੋ", "ਖਾਦ ਮੁੱਦਾ", "ਸਿੰਚਾਈ ਮੁੱਦਾ", "ਰੋਗ", "ਕੀਟ", "ਹੋਰ"]
    },
    mr: {
        // Nav & Hero
        home: "मुख्यपृष्ठ",
        myFarm: "माझा शेत",
        toDoList: "काम सूची",
        localTrend: "स्थानिक ट्रेंड",
        feedback: "अभिप्राय",
        search: "शोधा...",
        websiteLanguage: "वेबसाइट भाषा:",
        heroTitle: "ॲग्रोखेती",
        heroSubtitle: "पीएसए कंटेंट डेस्क द्वारे",
        heroDate: "22 सप्टेंबर, 2025",
        ctaButton: "शेतकऱ्यांसाठी उत्तम मदत",
        // Form
        formHeading: "फॉर्म तपशील प्रविष्ट करा",
        voiceInputTitle: "व्हॉइस इनपुट",
        voiceInputSubtitle: "आपले तपशील आपल्या स्थानिक भाषेत रेकॉर्ड करा.",
        formDetailsHeading: "शेतीचे तपशील",
        submitBtn: "सादर करा",
        locationLabel: "स्थान",
        landSizeLabel: "जमिनीचा आकार",
        cropLabel: "पिक",
        soilTypeLabel: "मातीचा प्रकार",
        soilCharacterLabel: "मातीचा प्रकार",
        irrigationLabel: "सिंचन स्रोत",
        sowingLabel: "पेरणी प्रकार",
        sowingDateLabel: "पेरणीची तारीख",
        cropStageLabel: "पिकाचा टप्पा",
        problemLabel: "सध्याची समस्या",
        uploadImageLabel: "फोटो अपलोड करा",
        // Footer
        footerLogo: "ॲग्रोखेती",
        footerSchemes: "योजना",
        footerMarketPrices: "बाजारभाव",
        footerContact: "संपर्क",
        // Dropdown Options
        locationOptions: ["स्थान निवडा", "ऑटो-डिटेक्ट GPS", "जिल्हा A", "जिल्हा B", "जिल्हा C"],
        landSizeOptions: ["<1 एकर", "1–5 एकर", "5+ एकर"],
        cropOptions: ["गहू", "तांदूळ", "मका", "सोयाबीन"],
        soilTypeOptions: ["वाळूची", "चिकणमाती", "पोयटा माती", "काळी"],
        soilCharacterOptions: ["मातीचा प्रकार निवडा", "माहित नाही", "काळी", "लाल", "पिवळी", "तपकिरी", "उच्च सुपीक", "कमी सुपीक"],
        irrigationOptions: ["कालवा", "ट्यूबवेल", "पावसावर अवलंबून", "तलाव"],
        sowingOptions: ["हाताने", "मशीनने"],
        cropStageOptions: ["टप्पा निवडा", "रोपण", "वनस्पति", "फुलांची", "कापणी"],
        problemOptions: ["समस्या निवडा", "खताचा प्रश्न", "सिंचनाचा प्रश्न", "रोग", "कीटक", "इतर"]
    },
    gu: {
        // Nav & Hero
        home: "ઘર",
        myFarm: "મારું ખેતર",
        toDoList: "કાર્ય સૂચિ",
        localTrend: "સ્થાનિક વલણ",
        feedback: "પ્રતિભાવ",
        search: "શોધો...",
        websiteLanguage: "વેબસાઇટ ભાષા:",
        heroTitle: "એગ્રોખેતી",
        heroSubtitle: "પીએસએ કન્ટેન્ટ ડેસ્ક દ્વારા",
        heroDate: "22 સપ્ટેમ્બર, 2025",
        ctaButton: "ખેડૂતોને વધુ સારું બનાવવામાં મદદ",
        // Form
        formHeading: "ફોર્મ વિગતો દાખલ કરો",
        voiceInputTitle: "વોઇસ ઇનપુટ",
        voiceInputSubtitle: "તમારી વિગતો તમારી સ્થાનિક ભાષામાં રેકોર્ડ કરો.",
        formDetailsHeading: "ખેતીની વિગતો",
        submitBtn: "સબમિટ કરો",
        locationLabel: "સ્થાન",
        landSizeLabel: "જમીનનું કદ",
        cropLabel: "પાક",
        soilTypeLabel: "માટીનો પ્રકાર",
        soilCharacterLabel: "માટીનો પ્રકાર",
        irrigationLabel: "સિંચાઈ સ્ત્રોત",
        sowingLabel: "વાવણી પ્રકાર",
        sowingDateLabel: "વાવણીની તારીખ",
        cropStageLabel: "પાકનો તબક્કો",
        problemLabel: "હાલની સમસ્યા",
        uploadImageLabel: "ફોટો અપલોડ કરો",
        // Footer
        footerLogo: "એગ્રોખેતી",
        footerSchemes: "યોજનાઓ",
        footerMarketPrices: "બજારના ભાવ",
        footerContact: "સંપર્ક",
        // Dropdown Options
        locationOptions: ["સ્થાન પસંદ કરો", "ઓટો-ડિટેક્ટ GPS", "જિલ્લો A", "જિલ્લો B", "જિલ્લો C"],
        landSizeOptions: ["<1 એકર", "1–5 એકર", "5+ એકર"],
        cropOptions: ["ઘઉં", "ચોખા", "મકાઈ", "સોયાબીન"],
        soilTypeOptions: ["રેતાળ", "ચીકણી", "ગોરાડુ", "કાળી"],
        soilCharacterOptions: ["માટીનો પ્રકાર પસંદ કરો", "ખબર નથી", "કાળી", "લાલ", "પીળી", "ભૂરી", "ઉચ્ચ ફળદ્રુપતા", "ઓછી ફળદ્રુપતા"],
        irrigationOptions: ["નહેર", "ટ્યુબવેલ", "વરસાદ આધારિત", "તળાવ"],
        sowingOptions: ["હાથથી", "મશીનથી"],
        cropStageOptions: ["તબક્કો પસંદ કરો", "બીજ", "વૃક્ષારોપણ", "ફૂલ", "લણણી"],
        problemOptions: ["સમસ્યા પસંદ કરો", "ખાતરનો મુદ્દો", "સિંચાઈનો મુદ્દો", "રોગ", "જંતુ", "અન્ય"]
    },
    bn: {
        // Nav & Hero
        home: "হোম",
        myFarm: "আমার খামার",
        toDoList: "করার তালিকা",
        localTrend: "স্থানীয় ট্রেন্ড",
        feedback: "ফিডব্যাক",
        search: "অনুসন্ধান...",
        websiteLanguage: "ওয়েবসাইট ভাষা:",
        heroTitle: "অ্যাগ্রোখেতি",
        heroSubtitle: "পিএসএ কন্টেন্ট ডেস্ক দ্বারা",
        heroDate: "22 সেপ্টেম্বর, 2025",
        ctaButton: "কৃষকদের উন্নত করতে সাহায্য",
        // Form
        formHeading: "ফর্মের বিবরণ লিখুন",
        voiceInputTitle: "ভয়েস ইনপুট",
        voiceInputSubtitle: "আপনার স্থানীয় ভাষায় আপনার বিবরণ রেকর্ড করুন।",
        formDetailsHeading: "খামারের বিবরণ",
        submitBtn: "জমা দিন",
        locationLabel: "অবস্থান",
        landSizeLabel: "জমির আকার",
        cropLabel: "ফসল",
        soilTypeLabel: "মাটির ধরন",
        soilCharacterLabel: "মাটির চরিত্র",
        irrigationLabel: "সেচের উৎস",
        sowingLabel: "বপনের ধরন",
        sowingDateLabel: "বপনের তারিখ",
        cropStageLabel: "ফসল পর্যায়",
        problemLabel: "বর্তমান সমস্যা",
        uploadImageLabel: "ছবি আপলোড করুন",
        // Footer
        footerLogo: "অ্যাগ্রোখেতি",
        footerSchemes: "স্কিম",
        footerMarketPrices: "বাজার মূল্য",
        footerContact: "যোগাযোগ",
        // Dropdown Options
        locationOptions: ["অবস্থান নির্বাচন করুন", "অটো-ডিটেক্ট GPS", "জেলা A", "জেলা B", "জেলা C"],
        landSizeOptions: ["<1 একর", "1–5 একর", "5+ একর"],
        cropOptions: ["গম", "ধান", "ভুট্টা", "সয়াবিন"],
        soilTypeOptions: ["বেলে", "কাদামাটি", "দোআঁশ", "কালো"],
        soilCharacterOptions: ["মাটির চরিত্র নির্বাচন করুন", "নিশ্চিত না", "কালো", "লাল", "হলুদ", "বাদামী", "উচ্চ উর্বরতা", "নিম্ন উর্বরতা"],
        irrigationOptions: ["খাল", "টিউবওয়েল", "বৃষ্টি নির্ভর", "পুকুর"],
        sowingOptions: ["ম্যানুয়াল", "মেশিন"],
        cropStageOptions: ["পর্যায় নির্বাচন করুন", "চারা", "উদ্ভিজ্জ", "ফুল", "ফসল কাটা"],
        problemOptions: ["সমস্যা নির্বাচন করুন", "সার সমস্যা", "সেচ সমস্যা", "রোগ", "পোকামাকড়", "অন্যান্য"]
    },
    ta: {
        // Nav & Hero
        home: "முகப்பு",
        myFarm: "எனது பண்ணை",
        toDoList: "செய்ய வேண்டியவை",
        localTrend: "உள்ளூர் போக்கு",
        feedback: "பின்னூட்டம்",
        search: "தேடல்...",
        websiteLanguage: "இணையதள மொழி:",
        heroTitle: "அக்ரோகேதி",
        heroSubtitle: "பிஎஸ்ஏ கன்டென்ட் டெஸ்க் மூலம்",
        heroDate: "செப்டம்பர் 22, 2025",
        ctaButton: "விவசாயிகளுக்கு மேம்படுத்த உதவும்",
        // Form
        formHeading: "படிவ விவரங்களை உள்ளிடவும்",
        voiceInputTitle: "குரல் உள்ளீடு",
        voiceInputSubtitle: "உங்கள் உள்ளூர் மொழியில் உங்கள் விவரங்களை பதிவு செய்யவும்.",
        formDetailsHeading: "பண்ணை விவரங்கள்",
        submitBtn: "சமர்ப்பிக்கவும்",
        locationLabel: "இடம்",
        landSizeLabel: "நில அளவு",
        cropLabel: "பயிர்",
        soilTypeLabel: "மண் வகை",
        soilCharacterLabel: "மண் தன்மை",
        irrigationLabel: "நீர்ப்பாசன மூலம்",
        sowingLabel: "விதைப்பு வகை",
        sowingDateLabel: "விதைப்பு தேதி",
        cropStageLabel: "பயிர் நிலை",
        problemLabel: "தற்போதைய சிக்கல்",
        uploadImageLabel: "படம் பதிவேற்றம்",
        // Footer
        footerLogo: "அக்ரோகேதி",
        footerSchemes: "திட்டங்கள்",
        footerMarketPrices: "சந்தை விலைகள்",
        footerContact: "தொடர்பு",
        // Dropdown Options
        locationOptions: ["இடம் தேர்வு செய்யவும்", "தானாக கண்டறிதல் GPS", "மாவட்டம் A", "மாவட்டம் B", "மாவட்டம் C"],
        landSizeOptions: ["<1 ஏக்கர்", "1–5 ஏக்கர்", "5+ ஏக்கர்"],
        cropOptions: ["கோதுமை", "அரிசி", "சோளம்", "சோயாபீன்"],
        soilTypeOptions: ["மணல்", "களிமண்", "வண்டல்", "கருப்பு"],
        soilCharacterOptions: ["மண் தன்மையை தேர்வு செய்யவும்", "உறுதியாக இல்லை", "கருப்பு", "சிவப்பு", "மஞ்சள்", "பழுப்பு", "அதிக வளத்தன்மை", "குறைந்த வளத்தன்மை"],
        irrigationOptions: ["கால்வாய்", "ஆழ்துளை கிணறு", "மழைநீர்", "குளம்"],
        sowingOptions: ["கையால்", "இயந்திரம்"],
        cropStageOptions: ["பயிர் வளர்ச்சியை தேர்வு செய்யவும்", "விதைப்பு", "தாவர வளர்ச்சி", "பூப்பு", "அறுவடை"],
        problemOptions: ["பிரச்சனையை தேர்வு செய்யவும்", "உரப் பிரச்சனை", "நீர்ப்பாசனப் பிரச்சனை", "நோய்", "பூச்சி", "மற்றவை"]
    },
    te: {
        // Nav & Hero
        home: "హోమ్",
        myFarm: "నా పొలం",
        toDoList: "చేయవలసినవి",
        localTrend: "స్థానిక పోకడ",
        feedback: "అభిప్రాయం",
        search: "వెతకండి...",
        websiteLanguage: "వెబ్‌సైట్ భాష:",
        heroTitle: "ఆగ్రోఖేతి",
        heroSubtitle: "పీఎస్ఏ కంటెంట్ డెస్క్ ద్వారా",
        heroDate: "సెప్టెంబర్ 22, 2025",
        ctaButton: "రైతులకు మెరుగైన సహాయం",
        // Form
        formHeading: "ఫారం వివరాలు నమోదు చేయండి",
        voiceInputTitle: "వాయిస్ ఇన్పుట్",
        voiceInputSubtitle: "మీ వివరాలను మీ స్థానిక భాషలో రికార్డ్ చేయండి.",
        formDetailsHeading: "పొలం వివరాలు",
        submitBtn: "సమర్పించు",
        locationLabel: "స్థానం",
        landSizeLabel: "భూమి పరిమాణం",
        cropLabel: "పంట",
        soilTypeLabel: "మట్టి రకం",
        soilCharacterLabel: "నేల లక్షణం",
        irrigationLabel: "పారిశుధ్య మూలం",
        sowingLabel: "విత్తన రకం",
        sowingDateLabel: "విత్తన తేదీ",
        cropStageLabel: "పంట దశ",
        problemLabel: "ప్రస్తుత సమస్య",
        uploadImageLabel: "చిత్రం అప్‌లోడ్ చేయండి",
        // Footer
        footerLogo: "ఆగ్రోఖేతి",
        footerSchemes: "పథకాలు",
        footerMarketPrices: "బజార్ ధరలు",
        footerContact: "సంప్రదించండి",
        // Dropdown Options
        locationOptions: ["స్థానం ఎంచుకోండి", "ఆటో-డిటెక్ట్ GPS", "జిల్లా A", "జిల్లా B", "జిల్లా C"],
        landSizeOptions: ["<1 ఎకరం", "1–5 ఎకరాలు", "5+ ఎకరాలు"],
        cropOptions: ["గోధుమ", "బియ్యం", "మొక్కజొన్న", "సోయాబీన్"],
        soilTypeOptions: ["ఇసుక", "బంకమట్టి", "లోమీ", "నలుపు"],
        soilCharacterOptions: ["నేల లక్షణం ఎంచుకోండి", "ఖచ్చితంగా తెలియదు", "నలుపు", "ఎరుపు", "పసుపు", "గోధుమ", "అధిక సారవంతం", "తక్కువ సారవంతం"],
        irrigationOptions: ["కాలువ", "బోరు బావి", "వర్షాధారం", "చెరువు"],
        sowingOptions: ["మాన్యువల్", "యంత్రం"],
        cropStageOptions: ["దశను ఎంచుకోండి", "నారు", "కూరగాయలు", "పూత", "కోత"],
        problemOptions: ["సమస్యను ఎంచుకోండి", "ఎరువుల సమస్య", "నీటిపారుదల సమస్య", "వ్యాధి", "తెగులు", "ఇతర"]
    },
    kn: {
        // Nav & Hero
        home: "ಮನೆ",
        myFarm: "ನನ್ನ ಹೊಲ",
        toDoList: "ಮಾಡಬೇಕಾದ ಕೆಲಸ",
        localTrend: "ಸ್ಥಳೀಯ ಟ್ರೆಂಡ್",
        feedback: "ಪ್ರತಿಕ್ರಿಯೆ",
        search: "ಹುಡುಕಿ...",
        websiteLanguage: "ವೆಬ್ಸೈಟ್ ಭಾಷೆ:",
        heroTitle: "ಅಗ್ರಿಖೇತಿ",
        heroSubtitle: "ಪಿಎಸ್ಎ ಕಂಟೆಂಟ್ ಡೆಸ್ಕ್ ಮೂಲಕ",
        heroDate: "ಸೆಪ್ಟೆಂಬರ್ 22, 2025",
        ctaButton: "ರೈತರಿಗೆ ಉತ್ತಮ ಸಹಾಯ ಮಾಡಲು",
        // Form
        formHeading: "ಫಾರ್ಮ್ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
        voiceInputTitle: "ಧ್ವನಿ ಇನ್ಪುಟ್",
        voiceInputSubtitle: "ನಿಮ್ಮ ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ನಿಮ್ಮ ವಿವರಗಳನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ.",
        formDetailsHeading: "ಫಾರ್ಮ್ ವಿವರಗಳು",
        submitBtn: "ಸಲ್ಲಿಸಿ",
        locationLabel: "ಸ್ಥಳ",
        landSizeLabel: "ಭೂಮಿ ಗಾತ್ರ",
        cropLabel: "ಬೆಳೆ",
        soilTypeLabel: "ಮಣ್ಣು ಪ್ರಕಾರ",
        soilCharacterLabel: "ಮಣ್ಣಿನ ಗುಣಲಕ್ಷಣ",
        irrigationLabel: "ನೀರಾವರಿ ಮೂಲ",
        sowingLabel: "ಬಿತ್ತನೆ ಪ್ರಕಾರ",
        sowingDateLabel: "ಬಿತ್ತನೆ ದಿನಾಂಕ",
        cropStageLabel: "ಬೆಳೆ ಹಂತ",
        problemLabel: "ಪ್ರಸ್ತುತ ಸಮಸ್ಯೆ",
        uploadImageLabel: "ಚಿತ್ರ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
        // Footer
        footerLogo: "ಅಗ್ರಿಖೇತಿ",
        footerSchemes: "ಯೋಜನೆಗಳು",
        footerMarketPrices: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು",
        footerContact: "ಸಂಪರ್ಕ",
        // Dropdown Options
        locationOptions: ["ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ", "ಆಟೋ-ಡಿಟೇಕ್ಟ್ GPS", "ಜಿಲ್ಲೆ A", "ಜಿಲ್ಲೆ B", "ಜಿಲ್ಲೆ C"],
        landSizeOptions: ["<1 ಎಕರೆ", "1–5 ಎಕರೆ", "5+ ಎಕರೆ"],
        cropOptions: ["ಗೋಧಿ", "ಅಕ್ಕಿ", "ಮೆಕ್ಕೆಜೋಳ", "ಸೋಯಾಬೀನ್"],
        soilTypeOptions: ["ಮರಳು", "ಕ್ಲೇ", "ಲೋಮಿ", "ಕಪ್ಪು"],
        soilCharacterOptions: ["ಮಣ್ಣಿನ ಗುಣಲಕ್ಷಣ ಆಯ್ಕೆಮಾಡಿ", "ಖಚಿತವಾಗಿಲ್ಲ", "ಕಪ್ಪು", "ಕೆಂಪು", "ಹಳದಿ", "ಕಂದು", "ಹೆಚ್ಚಿನ ಫಲವತ್ತತೆ", "ಕಡಿಮೆ ಫಲವತ್ತತೆ"],
        irrigationOptions: ["ಕಾಲುವೆ", "ಕೊಳವೆ ಬಾವಿ", "ಮಳೆ ಆಧಾರಿತ", "ಕೆರೆ"],
        sowingOptions: ["ಕೈಯಿಂದ", "ಯಂತ್ರದಿಂದ"],
        cropStageOptions: ["ಹಂತವನ್ನು ಆಯ್ಕೆಮಾಡಿ", "ಸಸಿ", "ಸಸ್ಯಕ", "ಹೂಬಿಡುವುದು", "ಕೊಯ್ಲು"],
        problemOptions: ["ಸಮಸ್ಯೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ", "ಗೊಬ್ಬರ ಸಮಸ್ಯೆ", "ನೀರಾವರಿ ಸಮಸ್ಯೆ", "ರೋಗ", "ಕೀಟ", "ಇತರೆ"]
    },
    ml: {
        // Nav & Hero
        home: "ഹോം",
        myFarm: "എന്റെ കൃഷി",
        toDoList: "ചെയ്യേണ്ട കാര്യങ്ങൾ",
        localTrend: "പ്രാദേശിക പ്രവണത",
        feedback: "അഭിപ്രായം",
        search: "തിരയുക...",
        websiteLanguage: "വെബ്സൈറ്റ് ഭാഷ:",
        heroTitle: "അഗ്രോഖേതി",
        heroSubtitle: "പിഎസ്എ കൺടെന്റ് ഡെസ്ക് വഴി",
        heroDate: "സെപ്റ്റംബർ 22, 2025",
        ctaButton: "കർഷകരെ മെച്ചപ്പെടുത്താൻ സഹായിക്കുക",
        // Form
        formHeading: "ഫോം വിശദാംശങ്ങൾ നൽകുക",
        voiceInputTitle: "വോയ്‌സ് ഇൻപുട്ട്",
        voiceInputSubtitle: "നിങ്ങളുടെ പ്രാദേശിക ഭാഷയിൽ നിങ്ങളുടെ വിവരങ്ങൾ രേഖപ്പെടുത്തുക.",
        formDetailsHeading: "കൃഷിഭൂമിയുടെ വിവരങ്ങൾ",
        submitBtn: "സമർപ്പിക്കുക",
        locationLabel: "സ്ഥലം",
        landSizeLabel: "ഭൂമി വലിപ്പം",
        cropLabel: "വിള",
        soilTypeLabel: "മണ്ണിന്റെ തരം",
        soilCharacterLabel: "മണ്ണിന്റെ സ്വഭാവം",
        irrigationLabel: "നനയ്ക്കൽ ഉറവിടം",
        sowingLabel: "വിത്ത് തരം",
        sowingDateLabel: "വിത്ത് തീയതി",
        cropStageLabel: "വിള ഘട്ടം",
        problemLabel: "നിലവിലെ പ്രശ്നം",
        uploadImageLabel: "ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
        // Footer
        footerLogo: "അഗ്രോഖേതി",
        footerSchemes: "പദ്ധതികൾ",
        footerMarketPrices: "വിപണി വിലകൾ",
        footerContact: "ബന്ധപ്പെടുക",
        // Dropdown Options
        locationOptions: ["സ്ഥലം തിരഞ്ഞെടുക്കുക", "ഓട്ടോ-ഡിറ്റക്റ്റ് GPS", "ജില്ല A", "ജില്ല B", "ജില്ല C"],
        landSizeOptions: ["<1 ഏക്കർ", "1–5 ഏക്കർ", "5+ ഏക്കർ"],
        cropOptions: ["ഗോതമ്പ്", "അരി", "ചോളം", "സോയാബീൻ"],
        soilTypeOptions: ["മണലിൽ", "കളിമണ്ണ്", "പശിമരാശി", "കറുപ്പ്"],
        soilCharacterOptions: ["മണ്ണിന്റെ സ്വഭാവം തിരഞ്ഞെടുക്കുക", "ഉറപ്പില്ല", "കറുപ്പ്", "ചുവപ്പ്", "മഞ്ഞ", "തവിട്ട്", "ഉയർന്ന ഫലഭൂയിഷ്ഠത", "കുറഞ്ഞ ഫലഭൂയിഷ്ഠത"],
        irrigationOptions: ["കനാൽ", "കുഴൽക്കിണർ", "മഴയെ ആശ്രയിച്ചുള്ള", "കുളം"],
        sowingOptions: ["കൈകൊണ്ട്", "മെഷീൻ കൊണ്ട്"],
        cropStageOptions: ["ഘട്ടം തിരഞ്ഞെടുക്കുക", "വിത്ത്", "സസ്യങ്ങൾ", "പൂവിടൽ", "വിളവെടുപ്പ്"],
        problemOptions: ["പ്രശ്നം തിരഞ്ഞെടുക്കുക", "വളം പ്രശ്നം", "നനയ്ക്കൽ പ്രശ്നം", "രോഗം", "കീടം", "മറ്റുള്ളവ"]
    },
    or: {
        // Nav & Hero
        home: "ମୁଖ୍ୟପୃଷ୍ଠା",
        myFarm: "ମୋର କ୍ଷେତ",
        toDoList: "କାର୍ଯ୍ୟ କରିବା ତାଲିକା",
        localTrend: "ସ୍ଥାନୀୟ ଟ୍ରେଣ୍ଡ",
        feedback: "ଫିଡବ୍ୟାକ",
        search: "ଖୋଜ...",
        websiteLanguage: "ୱେବସାଇଟ ଭାଷା:",
        heroTitle: "ଆଗ୍ରୋଖେତି",
        heroSubtitle: "ପିଏସଏ କଣ୍ଟେଣ୍ଟ ଡେସ୍କ ଦ୍ୱାରା",
        heroDate: "ସେପ୍ଟେମ୍ବର 22, 2025",
        ctaButton: "ଚାଷୀମାନଙ୍କୁ ଉନ୍ନତ କରିବାରେ ସାହାଯ୍ୟ",
        // Form
        formHeading: "ଫର୍ମର ବିବରଣୀ ଦିଅନ୍ତୁ",
        voiceInputTitle: "ଭଏସ ଇନପୁଟ",
        voiceInputSubtitle: "ଆପଣଙ୍କ ସ୍ଥାନୀୟ ଭାଷାରେ ଆପଣଙ୍କ ବିବରଣୀ ରେକର୍ଡ କରନ୍ତୁ।",
        formDetailsHeading: "କ୍ଷେତର ବିବରଣୀ",
        submitBtn: "ଦାଖଲ କରନ୍ତୁ",
        locationLabel: "ଅବସ୍ଥାନ",
        landSizeLabel: "ଜମିର ଆକାର",
        cropLabel: "ଫସଲ",
        soilTypeLabel: "ମାଟିର ପ୍ରକାର",
        soilCharacterLabel: "ମାଟିର ପ୍ରକାର",
        irrigationLabel: "ସିଞ୍ଚନ ଉତ୍ସ",
        sowingLabel: "ବିଜ ବିଜାଇ ପ୍ରକାର",
        sowingDateLabel: "ବିଜ ବିଜାଇ ତାରିଖ",
        cropStageLabel: "ଫସଲର ପର୍ଯ୍ୟାୟ",
        problemLabel: "ସାମ୍ପ୍ରତିକ ସମସ୍ୟା",
        uploadImageLabel: "ଫଟୋ ଅପଲୋଡ କରନ୍ତୁ",
        // Footer
        footerLogo: "ଆଗ୍ରୋଖେତି",
        footerSchemes: "ଯୋଜନା",
        footerMarketPrices: "ବଜାର ମୂଲ୍ୟ",
        footerContact: "ଯୋଗାଯୋଗ",
        // Dropdown Options
        locationOptions: ["ଅବସ୍ଥାନ ଚୟନ କରନ୍ତୁ", "ଅଟୋ-ଡିଟେକ୍ଟ GPS", "ଜିଲ୍ଲା A", "ଜିଲ୍ଲା B", "ଜିଲ୍ଲା C"],
        landSizeOptions: ["<1 ଏକର", "1–5 ଏକର", "5+ ଏକର"],
        cropOptions: ["ଗହମ", "ଧାନ", "ମକା", "ସୋୟାବିନ୍"],
        soilTypeOptions: ["ବାଲି", "ମାଟି", "ଦୋମଟ", "କଳା"],
        soilCharacterOptions: ["ମାଟିର ପ୍ରକାର ଚୟନ କରନ୍ତୁ", "ନିଶ୍ଚିତ ନୁହେଁ", "କଳା", "ଲାଲ", "ହଳଦିଆ", "ବାଦାମୀ", "ଉଚ୍ଚ ଉର୍ବରତା", "କମ୍ ଉର୍ବରତା"],
        irrigationOptions: ["କେନାଲ", "ଟ୍ୟୁବୱେଲ", "ବର୍ଷା ଉପରେ ନିର୍ଭର", "ପୋଖରୀ"],
        sowingOptions: ["ହାତରେ", "ମେସିନରେ"],
        cropStageOptions: ["ପର୍ଯ୍ୟାୟ ଚୟନ କରନ୍ତୁ", "ଚାରା", "ଉଦ୍ଭିଦ", "ଫୁଲ ଧରିବା", "ଅମଳ"],
        problemOptions: ["ସମସ୍ୟା ଚୟନ କରନ୍ତୁ", "ସାର ସମସ୍ୟା", "ଜଳସେଚନ ସମସ୍ୟା", "ରୋଗ", "କୀଟ", "ଅନ୍ୟ"]
    },
    as: {
        // Nav & Hero
        home: "গৃহ",
        myFarm: "মোৰ পাম",
        toDoList: "কৰিবলগীয়া তালিকা",
        localTrend: "স্থানীয় প্ৰৱণতা",
        feedback: "প্ৰতিক্ৰিয়া",
        search: "সন্ধান...",
        websiteLanguage: "ৱেবছাইটৰ ভাষা:",
        heroTitle: "এগ্ৰোখেতি",
        heroSubtitle: "পিএছএ কন্টেন্ট ডেস্ক দ্বাৰা",
        heroDate: "22 ছেপ্টেম্বৰ, 2025",
        ctaButton: "কৃষকসকলক উন্নত কৰাত সহায় কৰা",
        // Form
        formHeading: "ফৰ্মৰ বিৱৰণ দিয়ক",
        voiceInputTitle: "ভইচ ইনপুট",
        voiceInputSubtitle: "আপোনাৰ স্থানীয় ভাষাত আপোনাৰ বিৱৰণ ৰেকৰ্ড কৰক।",
        formDetailsHeading: "পামৰ বিৱৰণ",
        submitBtn: "দাখিল কৰক",
        locationLabel: "অৱস্থান",
        landSizeLabel: "মাটিৰ আকাৰ",
        cropLabel: "শস্য",
        soilTypeLabel: "মাটিৰ ধৰণ",
        soilCharacterLabel: "মাটিৰ চৰিত্ৰ",
        irrigationLabel: "সেচৰ উৎস",
        sowingLabel: "বপন ধৰণ",
        sowingDateLabel: "বপনৰ তাৰিখ",
        cropStageLabel: "শস্যৰ স্তৰ",
        problemLabel: "বৰ্তমানৰ সমস্যা",
        uploadImageLabel: "ছবি আপলোড কৰক",
        // Footer
        footerLogo: "এগ্ৰোখেতি",
        footerSchemes: "আঁচনি",
        footerMarketPrices: "বজাৰৰ দাম",
        footerContact: "যোগাযোগ",
        // Dropdown Options
        locationOptions: ["অৱস্থান বাছক", "অটো-ডিটেক্ট GPS", "জিলা A", "জিলা B", "জিলা C"],
        landSizeOptions: ["<1 একৰ", "1–5 একৰ", "5+ একৰ"],
        cropOptions: ["ঘেঁহু", "ধান", "মাকৈ", "ছয়াবিন"],
        soilTypeOptions: ["বালি", "চিনামাটি", "দোআঁশ", "কলা"],
        soilCharacterOptions: ["মাটিৰ চৰিত্ৰ বাছক", "নিশ্চিত নহয়", "কলা", "ৰঙা", "হালধীয়া", "মুগা", "উচ্চ উর্বৰতা", "কম উর্বৰতা"],
        irrigationOptions: ["খাল", "টিউবৱেল", "বৰষুণৰ ওপৰত নিৰ্ভৰশীল", "পুখুৰী"],
        sowingOptions: ["হাতেৰে", "যন্ত্ৰৰে"],
        cropStageOptions: ["স্তৰ বাছক", "গছপুলি", "উদ্ভিদ", "ফুলা", "শস্য চপোৱা"],
        problemOptions: ["সমস্যা বাছক", "সাৰৰ সমস্যা", "জলসিঞ্চনৰ সমস্যা", "ৰোগ", "কীট", "অন্যান্য"]
    },
    ur: {
        // Nav & Hero
        home: "صفحہ اول",
        myFarm: "میرا کھیت",
        toDoList: "کرنے کی فہرست",
        localTrend: "مقامی رجحان",
        irrigatfeedbacktion: "رائے",
        search: "تلاش کریں...",
        websiteLanguage: "ویب سائٹ کی زبان:",
        heroTitle: "ایگروکھیتی",
        heroSubtitle: "پی ایس اے کنٹینٹ ڈیسک کے ذریعے",
        heroDate: "22 ستمبر، 2025",
        ctaButton: "کاشتکاروں کو بہتر بنانے میں مدد کرنا",
        // Form
        formHeading: "فارم کی تفصیل درج کریں",
        voiceInputTitle: "صوتی ان پٹ",
        voiceInputSubtitle: "اپنی تفصیلات اپنی مقامی زبان میں ریکارڈ کریں۔",
        formDetailsHeading: "کھیت کی تفصیلات",
        submitBtn: "جمع کرائیں",
        locationLabel: "مقام",
        landSizeLabel: "زمین کا سائز",
        cropLabel: "فصل",
        soilTypeLabel: "مٹی کی قسم",
        soilCharacterLabel: "مٹی کی قسم",
        irrigationLabel: "آبپاشی کا ذریعہ",
        sowingLabel: "بوائی کی قسم",
        sowingDateLabel: "بوائی کی تاریخ",
        cropStageLabel: "فصل کا مرحلہ",
        problemLabel: "موجودہ مسئلہ",
        uploadImageLabel: "تصویر اپ لوڈ کریں",
        // Footer
        footerLogo: "ایگروکھیتی",
        footerSchemes: "اسکیمیں",
        footerMarketPrices: "بازار کی قیمتیں",
        footerContact: "رابطہ",
        // Dropdown Options
        locationOptions: ["مقام منتخب کریں", "آٹو-ڈیٹیکٹ GPS", "ضلع A", "ضلع B", "ضلع C"],
        landSizeOptions: ["<1 ایکڑ", "1–5 ایکڑ", "5+ ایکڑ"],
        cropOptions: ["گندم", "چاول", "مکئی", "سویابین"],
        soilTypeOptions: ["ریتیلی", "چکنی مٹی", "دومٹ", "کالی"],
        soilCharacterOptions: ["مٹی کی قسم منتخب کریں", "یقینی نہیں", "کالی", "سرخ", "پیلی", "بھوری", "اعلی زرخیزی", "کم زرخیزی"],
        irrigationOptions: ["نہر", "ٹیوب ویل", "بارش پر منحصر", "تالاب"],
        sowingOptions: ["ہاتھ سے", "مشین سے"],
        cropStageOptions: ["مرحلہ منتخب کریں", "پودا", "سبزیوں کا", "پھولوں کا", "کٹائی"],
        problemOptions: ["مسئلہ منتخب کریں", "کھاد کا مسئلہ", "آبپاشی کا مسئلہ", "بیماری", "کیڑے", "دیگر"]
    },
    sd: {
        // Nav & Hero
        home: "گھر",
        myFarm: "منهنجو کھیت",
        toDoList: "ڪم جي فهرست",
        localTrend: "مقامی رجحان",
        feedback: "رايا",
        search: "ڳولهيو...",
        websiteLanguage: "ويب سائيٽ جي ٻولي:",
        heroTitle: "ايگروکھیتي",
        heroSubtitle: "پي ايس اي ڪنٽينٽ ڊيسڪ جي طرفان",
        heroDate: "22 سيپٽمبر, 2025",
        ctaButton: "هاري کي بهتر بڻائڻ ۾ مدد ڪريو",
        // Form
        formHeading: "فارم جا تفصيل داخل ڪريو",
        voiceInputTitle: "آواز جي داخلا",
        voiceInputSubtitle: "پنهنجا تفصيل پنهنجي مقامي ٻولي ۾ رڪارڊ ڪريو.",
        formDetailsHeading: "کھیت جا تفصيل",
        submitBtn: "جمع ڪرايو",
        locationLabel: "جاءِ",
        landSizeLabel: "زمين جو سائيز",
        cropLabel: "فصل",
        soilTypeLabel: "مٽي جو قسم",
        soilCharacterLabel: "مٽي جو قسم",
        irrigationLabel: "آبپاشي جو ذريعو",
        sowingLabel: "پوک جو قسم",
        sowingDateLabel: "پوک جي تاريخ",
        cropStageLabel: "فصل جو مرحلو",
        problemLabel: "هاڻوڪو مسئلو",
        uploadImageLabel: "تصوير اپلوڊ ڪريو",
        // Footer
        footerLogo: "ايگروکھیتي",
        footerSchemes: "اسڪيمون",
        footerMarketPrices: "مارڪيٽ جا قدر",
        footerContact: "رابطو",
        // Dropdown Options
        locationOptions: ["جاءِ چونڊيو", "آٽو-ڊيٽيڪٽ GPS", "ضلع A", "ضلع B", "ضلع C"],
        landSizeOptions: ["<1 ايڪڙ", "1–5 ايڪڙ", "5+ ايڪڙ"],
        cropOptions: ["ڪڻڪ", "چانور", "مڪئي", "سويابين"],
        soilTypeOptions: ["واريء", "چيڪني", "دومٽ", "ڪاري"],
        soilCharacterOptions: ["مٽي جو قسم چونڊيو", "پڪ ناهي", "ڪاري", "لال", "پيلي", "گهرڙي", "وڌيڪ زرخيز", "گهٽ زرخيز"],
        irrigationOptions: ["واهه", "ٽيوب ويل", "برساتي", "تلاءُ"],
        sowingOptions: ["هٿ سان", "مشين سان"],
        cropStageOptions: ["مرحلو چونڊيو", "ٻوٽو", "وڌندڙ", "گل", "ڪٽائي"],
        problemOptions: ["مسئلو چونڊيو", "ڀاڻ جو مسئلو", "آبپاشي جو مسئلو", "بيماري", "ڪيڙا", "ٻيا"]
    },
    sa: {
        // Nav & Hero
        home: "गृहम्",
        myFarm: "मम क्षेत्रम्",
        toDoList: "करणीयसूची",
        localTrend: "स्थानीयप्रवृत्तिः",
        feedback: "प्रतिपुष्टिः",
        search: "अन्वेषणम्...",
        websiteLanguage: "जालपुटभाषा:",
        heroTitle: "कृषिभूमः",
        heroSubtitle: "पीएसए विषयवस्तु-डेस्कद्वारा",
        heroDate: "सेप्टेम्बर् 22, 2025",
        ctaButton: "कृषकान् उन्नतं कर्तुं साहाय्यम्",
        // Form
        formHeading: "रूपस्य विवरणं प्रविशतु",
        voiceInputTitle: "ध्वनि-निवेशः",
        voiceInputSubtitle: "स्वतः विवरणं स्वभाषया अभिलेखयतु।",
        formDetailsHeading: "कृषिक्षेत्रविवरणानि",
        submitBtn: "प्रस्तुतम्",
        locationLabel: "स्थानम्",
        landSizeLabel: "भूमेः आकारः",
        cropLabel: "कृषिः",
        soilTypeLabel: "मृत्तिका प्रकारः",
        soilCharacterLabel: "मृत्तिकायाः लक्षणम्",
        irrigationLabel: "सिंचन स्रोतः",
        sowingLabel: "बीजन प्रकारः",
        sowingDateLabel: "बीजनस्य तिथिः",
        cropStageLabel: "सस्यस्य अवस्था",
        problemLabel: "वर्तमानसमस्या",
        uploadImageLabel: "चित्रं प्रेषयतु",
        // Footer
        footerLogo: "कृषिभूमः",
        footerSchemes: "योजनाः",
        footerMarketPrices: "आपणमूल्यानि",
        footerContact: "सम्पर्कः",
        // Dropdown Options
        locationOptions: ["स्थानं चिनोतु", "स्वयं-अन्वेषण GPS", "मण्डलम् A", "मण्डलम् B", "मण्डलम् C"],
        landSizeOptions: ["<1 एकरम्", "1–5 एकरम्", "5+ एकरम्"],
        cropOptions: ["गोधूमः", "तण्डुलः", "मक्का", "सोयाबीन"],
        soilTypeOptions: ["सिकतामयम्", "मृत्तिका", "लोमी", "कृष्णम्"],
        soilCharacterOptions: ["मृत्तिकायाः लक्षणं चिनोतु", "निश्चितं नास्ति", "कृष्णम्", "रक्तम्", "पीतम्", "पलाशि", "उच्चा उर्वरता", "न्यूनोर्वरता"],
        irrigationOptions: ["नदी", "कूपः", "वर्षाश्रितः", "सरसः"],
        sowingOptions: ["हस्तेन", "यन्त्रेण"],
        cropStageOptions: ["अवस्थां चिनोतु", "बीजकम्", "वनस्पतिः", "पुष्पम्", "सस्यच्छेदः"],
        problemOptions: ["समस्यां चिनोतु", "उर्वरकसम्बंधी", "सिंचनसम्बंधी", "रोगः",
